"""routers/insights.py — /api/insights, /api/analytics/income, /api/analytics/efficiency.

No shared prefix (the three paths don't share a common root), so each route
carries its full literal path — identical to the original api.py URLs.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Request

from dependencies import get_current_user, limiter
from services import insights_service

router = APIRouter(tags=["insights"])


@router.get("/api/insights")
@limiter.limit("60/minute")
def get_insights(request: Request, current_user: dict = Depends(get_current_user)) -> dict:
    """Return plain-English financial insights generated by the InsightEngine."""
    return insights_service.get_insights(current_user["id"])


@router.get("/api/analytics/income")
@limiter.limit("60/minute")
def analytics_income(request: Request, current_user: dict = Depends(get_current_user)) -> dict:
    return insights_service.get_income_analytics(current_user["id"])


@router.get("/api/analytics/efficiency")
@limiter.limit("60/minute")
def analytics_efficiency(request: Request, current_user: dict = Depends(get_current_user)) -> list[dict]:
    return insights_service.get_efficiency_analytics(current_user["id"])
